### ISSUE TITLE
Solve this problem

### ISSUE THREAD

**Issue by yazan-mmw** [basarozcan/vue-tailwindcss-typeahead#1]
Error in created hook: "TypeError: Cannot read property 'name' of undefined"

**Comment by yazan-mmw** [comment]
I solve this when replace this code
in created()

` if(this.selectedItem){
      this.selectedItem = selected[0].name
      this.search = selected[0].name
}`

**Comment by wilmeragsgh** [comment]
In my case, the change was `if(this.selectedData != 0){` -> `if(this.selectedData){` around line 109. Maybe that's also what you mean @yazan-mmw , thanks!
