### ISSUE TITLE
Not compatible with TailwindCSS 3.0.7

### ISSUE THREAD

**Issue by eugenevk** [basarozcan/vue-tailwindcss-typeahead#7]
![image](https://user-images.githubusercontent.com/19785727/147552665-1b94f3ac-884e-4f32-863d-8111e5495b28.png)

Hi @basarozcan, is there a chance you can fix this? Thanks

**Comment by basarozcan** [comment]
It will be checked @eugenevk

**Comment by mouradsm** [comment]
@basarozcan It would be really good =)

**Comment by basarozcan** [comment]
New version released with vue3 and tailwindcss3 support @mouradsm @eugenevk
