### ISSUE TITLE
Update README for Vue3

### ISSUE THREAD

**Issue by wonder95** [basarozcan/vue-tailwindcss-typeahead#9]
In attempting to implement this in a Vue 3 app, I noticed that the README has not been updated since Vue 3 support was [added](https://github.com/basarozcan/vue-tailwindcss-typeahead/commit/853d4d7bfffcc8d6b7b2535bf4beaf9a9d17e05a). 
In particular, the name was changed from `VueTailwindcssTypeahead` to `VueTwTypeahead`, which means that the import in `app.js` needs to be:
```
import {VueTwTypeahead} from 'vue-tailwindcss-typeahead.vue';

app.use(VueTwTypeahead)
```
and then in the component
```
<script setup>
import {VueTwTypeahead} from 'vue-tailwindcsscss-typeahead'

<vue-tw-typeahead
    :lists="list"
    @selected="selectedData"
    :ignoredList="selectedItemIds"
    :clearInputWhenClicked="false"
    :inputClass="['w-full','px-3','py-2','border','border-gray-400','rounded-lg','outline-none','focus:shadow-outline']"
    placeholder="Please write a city name"
>
</vue-tw-typeahead>

**Comment by basarozcan** [comment]
Thank you for your notification, README updated 👍
